name: userstogsuite
description: Generador de usuarios para GSuite desde Séneca.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependencies:
  args: ^1.6.0
